### ISSUE TITLE
netuserenum Feature Request: Enabled Users Only

### ISSUE THREAD

**Issue by curi0usJack** [trustedsec/CS-Situational-Awareness-BOF#1]
Looks like you can specify some type of filter in the domain user enumeration request:

![image](https://user-images.githubusercontent.com/5608516/90793701-ac00d780-e2d1-11ea-997c-a736dcdee360.png)

Would be useful to have either a switch if possible or another BOF command entirely that only pulls back enabled users only. Makes for a better brute force target list.

**Comment by curi0usJack** [comment]
Lame. Not that simple it seems. Would probably have to interrogate UAC on every user to filter out disabled ones.

https://docs.microsoft.com/en-us/windows/win32/api/lmaccess/nf-lmaccess-netuserenum

**Comment by freefirex** [comment]
Feature added
