### ISSUE TITLE
Weird parameter gathering for dir BOF

### ISSUE THREAD

**Issue by LostAquilae** [trustedsec/CS-Situational-Awareness-BOF#121]
Hello there,

I noticed something that appeared strange to me. For the dir BOF, when gathering the arguments, you use BeaconDataShort Beacon API function to retrieve the argument for subdirs (/s). Code snippet is here : https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/2967208383dcedf36314693dd23fa8d2088d7dc4/src/SA/dir/entry.c#L120

My question is the following: Why extract this parameter as a short whereas in README, the line for using dir BOF displays this : dir [directory] [/s]. It seems like it neccesitates a string but you gather the argument by extracting a short ?

Is there some hidden behavior here that I didn't see ?

Thanks for the consideration

**Comment by freefirex** [comment]
Yes there is some behavior that was missed.

You want to also look at the packing string on https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/2967208383dcedf36314693dd23fa8d2088d7dc4/SA/SA.cna#L128

This shows that we have subdirs set to 0 if /s is not found and 1 if it is found.  Then we pack a short and send that 0 or 1 based on if /s was in the argument string
