### ISSUE TITLE
Ability for storing output in text file for sa-sc-enum

### ISSUE THREAD

**Issue by yobroda** [trustedsec/CS-Situational-Awareness-BOF#123]
Hi, I was trying to learn sliver when I was redirected here from sliver armory. When executing sa-sc-enum, help menu shows there are two arguments, flags and target server 

I was wondering, if you guys can help me  with some steps on how can i capture such a huge output in a text file instead of stdout on terminal

**Comment by freefirex** [comment]
We don't specifically manage the sliver integration of our various beacon object files.
Likely you want a feature request against sliver to specifically allow redirection of any given command to a file.

Your other option would be using a command like `tee` to capture your entire interaction with sliver to a file, then use a text editor to search that after the fact.  tee itself will display the color codes by default so you would end up needing to work around that.

**Comment by yobroda** [comment]
Thanks, it was indeed a nice workaround to use tee!!
