### ISSUE TITLE
nslookup crash

### ISSUE THREAD

**Issue by funnybananas** [trustedsec/CS-Situational-Awareness-BOF#125]
After recompiling nslookup, it seems to crash the beacon. If compiled as an EXE, it generates an AppCrash (0xc000005). Pre-compiled BOF works. Have tested with MingW 12.

Looks like it might be crashing from trying to read from a null ptr and it looks like most likely from the (line 219 and 228)  `server = *server == 0 ? NULL : server` line in `go` and `main`. Could be wrong, but this is what I saw when I looked at it with a debugger.

**Comment by funnybananas** [comment]
it could also be that MingW 12 uses UCRT instead of MSVCRT as the default now. Using MingW 11 seemed to have worked.

**Comment by freefirex** [comment]
`server = *server == 0 ? NULL : server` should be dereferencing the value from BeaconDataExtract which will be a pointer to a single null terminator, enabling the ternary to work properly (I use that pattern in many of the BOF's)

As the code hasn't changed in the last 3 years I suspect you are correct in that it is something new that modern mingw is doing which isn't being handled properly by the loaders.  I'll close the issue out on this end for now given I believe its strongly likely the BOF loader is where modifications will be needed to support newer compiler outputs.

**Comment by funnybananas** [comment]
I may have spoken too soon. My previous test with MingW11 wasn't accurate, it seems that it still doesn't work with that version. Other BOFs compile and run fine, just for some reason not nslookup, still crashes the beacon.

**Comment by freefirex** [comment]
Alright I've made a note to take a look at this early next week and I'll do some testing on my end

**Comment by funnybananas** [comment]
thanks! if it helps, after some more digging, it looks like it might have something to do with referencing the pdns records in the do/while loop.

**Comment by funnybananas** [comment]
maybe it's stack related? It seems that if I reduce the amount of "internal_printf" calls it works. Though I don't have that issue with any other BOF in the repo, and others call it much more.

**Comment by freefirex** [comment]
Sorry for the delay, I had a few projects come up at work last week that took priority.

I am starting to look at this today and I do recreate your issue when I recompile this BOF.  I'll report back with my results once I have a fix.

**Comment by freefirex** [comment]
This is the disassembly where the crash occurred
![image](https://github.com/user-attachments/assets/7d06b4df-d709-4962-80a0-039a87c60d15)

This pattern is a jump table, which appears to be only inserted in newer versions of mingw / gcc. (Originally this is why I didn't use a switch statement to avoid this)

Since mingw /gcc have wised up to my antics we now need to explicitly tell it not to generate a jump table with -fno-jump-tables.  After adding that into our bof compile it runs fine again.
