### ISSUE TITLE
Correctness issues

### ISSUE THREAD

**Issue by JohnLaTwC** [trustedsec/CS-Situational-Awareness-BOF#19]
## Issue 1
In `go()` a call is made to `task_list()` with a variable `server` read from a Beacon with `BeaconDataExtract`.
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/tasklist/entry.c#L114

This is passed in to `Wmi_Connect` as `pwszServer`. Besides being null terminated, I don't see a length constraint on `pwszServer`

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/tasklist/entry.c#L43

The possibility for a heap overrun exists because of the insecure use of `wcscpy` to a buffer that is a maximum size of `MAX_PATH*sizeof(wchar_t)`
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/common/wmi.c#L116

## Issue 2
There is a correctness issue on this line due to a copy/paste error.  `pwszNameSpace` is the allocated string, but the variable `pwszServer` is checked.
```diff
	pwszNameSpace = (LPWSTR)KERNEL32$HeapAlloc(KERNEL32$GetProcessHeap(), HEAP_ZERO_MEMORY, MAX_PATH*sizeof(wchar_t));
-	if (NULL == pwszServer)
+	if (NULL == pwszNameSpace)
```
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/common/wmi.c#L125

## Issue 3
The possibility for a wild free exists in `validate_driver()`:

Take the case where the for loop completes successfully once. At this point, the variables `certificate_context`, `certificate_header`, and `certificate` have been freed but not set back to NULL. On an nth pass through loop, take this case:
if the allocation for `certificate_header` fails on line `98` and it jumps to the clear label on line `102`, both `certificate` and `certificate_context` are non-NULL from a previous time through the loop but will have free routines called on them resulting in a wild free. There are similar issues in the loop on the other `goto clear` jumps. After freeing the memory, it should be set to `NULL`.

```diff
		clear:
		if (certificate_context)
+		{
			CRYPT32$CertFreeCertificateContext(certificate_context);
+			certificate_context = NULL;
+		}
		if(certificate_header)
+		{
			intFree(certificate_header);
+			certificate_header = NULL;
+		}
		if(certificate)
+		{
			intFree(certificate);
+			certificate = NULL;
+		}
```
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/driversigs/entry.c#L137

## Issue 4

Memory leak in `getIPInfo()`. There are early function exits which do not release the memory belonging to `info`.

```diff
    IP_ADAPTER_INFO * info = intAlloc(sizeof(IP_ADAPTER_INFO) * 32); // have to keep stack < 4K
...
    if(IPHLPAPI$GetNetworkParams(pFixedInfo, &netOutBufLen) == ERROR_BUFFER_OVERFLOW){
        pFixedInfo = (FIXED_INFO *)intAlloc(netOutBufLen);
        if (pFixedInfo == NULL)
        {

			BeaconPrintf(CALLBACK_ERROR, "could not get network adapter info");
            return;   
! Leaks memory belonging to info 
        }
        if (IPHLPAPI$GetNetworkParams(pFixedInfo, &netOutBufLen) != NO_ERROR)
        {
            if (pFixedInfo){
                intFree(pFixedInfo);
            }
			BeaconPrintf(CALLBACK_ERROR, "could not get network adapter info");
            return;  
! Leaks memory belonging to info 
        }

    }
```

The early returns are on these lines: 
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/ipconfig/entry.c#L32

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/ipconfig/entry.c#L40

## Issue 5

Handle leak in `PrintModules()` on early function return.

```diff
    hProcess = KERNEL32$OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, processID);
...
    // Get size needed before requesting hMods
    if(!PSAPI$EnumProcessModulesEx(hProcess, 0, 0, &cbNeeded, LIST_MODULES_ALL)){
        internal_printf("Failed to enumerate modules\n");
        return 1;   
! Fails to call CloseHandle on hProcess
    }

```

The early return is here: 
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/listmods/entry.c#L78

## Issue 6

Registry handle leak in `Reg_GetValue()` on early function return.

```diff
		dwRet = ADVAPI32$RegConnectRegistryA(hostname, hivekey, &RemoteKey);
...
		dwRet = ADVAPI32$RegOpenKeyExA(RemoteKey, keystring, 0, KEY_READ, &key);
...
    ValueData = intAlloc(size);
    if (ValueData == NULL){
        BeaconPrintf(CALLBACK_ERROR, "Failed to allocate memory\n");
        return E_OUTOFMEMORY;   
! fails to free registry key handles done at the END: label
    }
```

This is where the keys are normally freed:
```diff
    END:
...
! early function exits fail to release allocated resources as done here
    if(key)
     	ADVAPI32$RegCloseKey(key);
	if(RemoteKey)
		ADVAPI32$RegCloseKey(RemoteKey);

```

The early return is here: 
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/reg_query/entry.c#L161

## Issue 7

Invalid permissions specified in call to ADVAPI32$OpenServiceA (SC_MANAGER_CONNECT  is a permission for `ADVAPI32$OpenSCManagerA`, not `ADVAPI32$OpenServiceA`

```diff
		if ((scService = ADVAPI32$OpenServiceA(scManager, cpServiceName, SC_MANAGER_CONNECT | GENERIC_READ)) == NULL)   
! SC_MANAGER_CONNECT is not a service permission
```

Even though it is incorrect, it doesn't cause any harm because `SC_MANAGER_CONNECT` maps to `0x0001` which is `SERVICE_QUERY_CONFIG`

`SC_MANAGER_CONNECT` should be removed because `GENERIC_READ` is sufficient to cover the calls to `get_service_config` and `get_service_status`.

```

GENERIC_READ --->  
    STANDARD_RIGHTS_READ
    SERVICE_QUERY_CONFIG
    SERVICE_QUERY_STATUS
    SERVICE_INTERROGATE
    SERVICE_ENUMERATE_DEPENDENTS
```

See these places for instances of this issue::
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/sc_qc/entry.c#L167

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/sc_qfailure/entry.c#L86

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/sc_qdescription/entry.c#L21

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/sc_qtriggerinfo/entry.c#L122

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/sc_query/entry.c#L177

## Issue 8

Leak because Vserver.bstrVal is not freed after usage.

```
	Vserver.bstrVal = OLEAUT32$SysAllocString(server);
```
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/schtasksenum/entry.c#L59

Same issue here:
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/schtasksquery/entry.c#L54

Release is not called on `pSubfolders`

```
		ITaskFolderCollection *pSubfolders = NULL;
...
		pCurFolder->lpVtbl->GetFolders(pCurFolder, 0, &pSubfolders);
```
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/schtasksenum/entry.c#L83

## Issue 9

Handle leak on `hToken` because `CloseHandle` path is skipped on early function exits

```diff
    if (ADVAPI32$OpenProcessToken(KERNEL32$GetCurrentProcess(), TOKEN_READ, &hToken))
    {
        ADVAPI32$GetTokenInformation(hToken,
                            TokenType,
                            NULL,
                            dwLength,
                            &dwLength);

        if (KERNEL32$GetLastError() == ERROR_INSUFFICIENT_BUFFER)
        {
            pTokenInfo = intAlloc(dwLength);
            if (pTokenInfo == NULL)
            {
                //printf("ERROR: not enough memory to allocate the token structure.\r\n");
                return NULL;         
! doesn't call CloseHandle on hToken
            }
        }

        if (!ADVAPI32$GetTokenInformation(hToken, TokenType,
                                 (LPVOID)pTokenInfo,
                                 dwLength,
                                 &dwLength))
        {
            //printf("ERROR 0x%x: could not get token information.\r\n", GetLastError());
            intFree(pTokenInfo);
            return NULL;		 
! doesn't call CloseHandle on hToken
        }

```
Early exits
https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/whoami/entry.c#L61

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/whoami/entry.c#L72

**Comment by freefirex** [comment]
Wow this is extremely detailed, thank you for the very thorough second look.

I'll get to fixing these issues tomorrow!

**Comment by freefirex** [comment]
slowly going through and running scan-build / cppcheck on all of these.  probably will be a couple more days.

On issue 8, I believe the Vserver bstr entry is being freed from the VariantClear call under the end: label.  Documentation for that function claims it will free the string if the variant type is a bstr.

https://github.com/trustedsec/CS-Situational-Awareness-BOF/blob/075fa2394342d740fea16f0acb3b11ac96af1524/src/SA/schtasksenum/entry.c#L184

**Comment by freefirex** [comment]
All issues pointed out have been addressed.  Thanks again!

**Comment by JohnLaTwC** [comment]
Awesome work!
