### ISSUE TITLE
Feature Request for nslookup: Support for reverse lookups

### ISSUE THREAD

**Issue by SoloDefend** [trustedsec/CS-Situational-Awareness-BOF#31]
Looking for reverse lookup support with the nslookup BOF. 

If I do nslookup 10.10.10.10 it only returns the A record for the IP but no hostname. If I try the below options I get DNS errors.
nslookup 10.10.10.10.in-addr.arpa
nslookup 10.10.10.10 PTR

**Comment by freefirex** [comment]
PTR records are supported, but currently you are targeting an IP that doesn't have a PTR record registered (unless its registered in your testing domain) and you are using the incorrect format.

Please see these tests / examples
10.10.10.10 being invalid
![Screen Shot 2021-01-22 at 11 54 35 AM](https://user-images.githubusercontent.com/3172440/105527158-f33c2b80-5ca8-11eb-8101-7ab7277507a6.png)
A valid PTR lookup
![Screen Shot 2021-01-22 at 11 55 04 AM](https://user-images.githubusercontent.com/3172440/105527263-1535ae00-5ca9-11eb-8ac2-f21c3bf36064.png)
How to perform the lookup using our nslookup bof and showing the help for how to format the query
![Screen Shot 2021-01-22 at 11 55 44 AM](https://user-images.githubusercontent.com/3172440/105527332-2bdc0500-5ca9-11eb-8ad7-fc64af5c1399.png)

**Comment by SoloDefend** [comment]
Yeah that's how I had it formatted (omitting the 0) forgot to add PTR to my request here. Was using for internal recon so it looks like the domain doesn't have pointers. Thanks for the clarification.
