### ISSUE TITLE
netuser cannot parse usernames with a dash

### ISSUE THREAD

**Issue by docFord** [trustedsec/CS-Situational-Awareness-BOF#32]
During an engagement I attempted to search for a user with a dash in the name e.g. - "netuser t-testuser domain.com" and the BOF returns the error `Failed to get user info`

I also attempted to wrap the username in quotes, and escape the dash with a backslash. All attempted returned the error above. I am able to find the user with a traditional net user lookup via beacon `run net user t-testuser /domain`

**Comment by freefirex** [comment]
triage with user found issue was not isolated to the bof itself
