### ISSUE TITLE
bug in 'whoami'

### ISSUE THREAD

**Issue by yanghaoi** [trustedsec/CS-Situational-Awareness-BOF#80]
Hi, Your bof is very nice! But i fond a litter bug in zh-cn local windows, it's look like（DispName words Full display）: 
wrong：
![image](https://user-images.githubusercontent.com/21354684/181919295-a6884a5e-c4ac-4454-a834-08195e6a991b.png)
True:
![image](https://user-images.githubusercontent.com/21354684/181919333-47ccc11f-50d5-4e0e-91b5-18d191ae94d7.png)

**Comment by yanghaoi** [comment]
I try fix it , but i not found syntax error... o.0

**Comment by freefirex** [comment]
Hello thank you for this report.

I'm honestly not used to working with character maps outside of english.  I'm having difficulty understanding what the bug is.

Is the description being cut off or is it the enabled / Disabled showing in english?

**Comment by yanghaoi** [comment]
Yes, the bug’s really hard to understand.I’ll try to use w_char* and
LookupPrivilegeDisplayNameW fix this🤪

freefirex ***@***.***>于2022年8月1日 周一21:05写道：

**Comment by yanghaoi** [comment]
Hello, I use  "LookupPrivilegeNameW" and  "WideCharToMultiByte"   fix the bug. 

![image](https://user-images.githubusercontent.com/21354684/183381764-8d2e568d-0106-496e-b9b4-bcb1dd9e06e0.png)

**Comment by freefirex** [comment]
Awesome, I am open to accepting a pull request if you have code that fixes the bug as stated.

Otherwise I'll address this the next time I'm going through issue lists / pull requests and working this codebase.

**Comment by yanghaoi** [comment]
Thanks, I’ll do it this week. 😀

freefirex ***@***.***>于2022年8月8日 周一20:59写道：

**Comment by yanghaoi** [comment]
Hello,I create a repository [BOF_whoami ]( https://github.com/yanghaoi/BOF_whoami ) fixes some bugs, thank you.
