### ISSUE TITLE
Remote wmi receives access denied after using make_token

### ISSUE THREAD

**Issue by Octoberfest7** [trustedsec/CS-Situational-Awareness-BOF#94]
I have experienced an issue using the wmi_query as well as the tasklist BOF in which trying to use either BOF on a remote machine with a token created using make_token returns Access Denied.

In a beacon running as the user DA ( a Domain Admin in the network) I am successfully able to use the wmi_query and tasklist BOFs remotely. 

![image](https://user-images.githubusercontent.com/91164728/215282013-abc6ee02-7abc-425d-ae2e-5e22fa3b30c0.png)

In a beacon running as SYSTEM, I use make_token with DA's creds.  I am successfully able to use the created token, as demonstrated by doing a ls \\dev-dc\c$ as well as using shell wmic ...

I am unable however to use wmi_query or tasklist remotely, receiving an Access Denied error.  I'm running CobaltStrike version 4.7.2 and have confirmed this using the latest branch of CS-Situational-Awareness-BOF

![image](https://user-images.githubusercontent.com/91164728/215282292-556ad52e-d12c-4bba-9de8-14da4f7a7517.png)

**Comment by freefirex** [comment]
Tracked this down and got it fixed, thanks for the report!

**Comment by Octoberfest7** [comment]
Great, thanks so much for your work!
